name: CICD

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking the code
      uses: actions/checkout@v2

    - name: Setting my python environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Installing flask library
      run: |
        pip3 install flask requests

    - name: Running my flask app
      run: |
        python3 flask_app.py

    - name: Testing app with unittests
      run: |
        python3 test_flaskApp.py

    
